=== arXiv/arxiv-canonical/schema-extended/New.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "definitions": {
      "affiliation": {
        "description": "Institutional affiliation",
        "type": "object",
        "properties": {
          "name": {
            "description": "The fullest representation of the affiliation's name",
            "type": "string"
          },
          "ror_id": {
            "description": "Research Organization Registry ID",
            "oneOf": [
              {"type": "string"},
              {"type": "null"}
            ]
          }
        }
      },
      "content_type": {
        "$comment": "TODO: a more complete enumeration of possible content types",
        "type": "string",
        "enum": ["article", "thesis", "proceeding", "monograph"]
      },
      "collaboration": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The fullest representation of the collaborations's name",
            "type": "string"
          },
          "language": {
            "description": "Language used to identify the collaboration.",
            "oneOf": [
              {"type": "string"},
              {"type": "null"}
            ]
          }
        }
      },
      "doi": {
        "type": "string",
        "pattern": "^10.[0-9]{4,9}/[-._;()/:a-zA-Z0-9]+$"
      },
      "license": {
        "type": "object",
        "properties": {
          "@type": {
            "type": "string"
          },
          "href": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "person": {
        "type": "object",
        "properties": {
          "@type": {
            "type": "string"
          },
          "full_name": {
            "description": "The fullest representation of the person's name available in arXiv metadata.",
            "type": "string"
          },
          "last_name": {
            "description": "The family or surname part of the person's name, if available.",
            "oneOf": [
              {"type": "string"},
              {"type": "null"}
            ]
          },
          "first_name": {
            "description": "The personal or forename part of the person's name, if available.",
            "oneOf": [
              {"type": "string"},
              {"type": "null"}
            ]
          },
          "suffix": {
            "description": "The suffix part of the person's name, if available.",
            "oneOf": [
              {"type": "string"},
              {"type": "null"}
            ]
          },
          "affiliation": {
            "description": "Institutional affiliation as entered at the time of submission, if available.",
            "$ref": "#/definitions/affiliation"
          },
          "orcid": {
            "description": "ORCID identifier, if available.",
            "oneOf": [
              {"type": "string"},
              {"type": "null"}
            ]
          },
          "author_id": {
            "description": "arXiv author identifier, if available.",
            "oneOf": [
              {"type": "string"},
              {"type": "null"}
            ]
          },
          "is_submitter": {
            "description": "Indicates whether this person is the submitter of this submission",
            "type": "boolean"
          }
        },
        "required": [
          "full_name"
        ]
      },
      "reference": {
        "type": "object",
        "properties": {
          "reference_string": {
            "type": "string"
          }
        }
      },
      "versioned_identifier": {
        "type": "string",
        "pattern": "^(([0-9]{4}\\.[0-9]{4,5})|([a-z\\-]+\\/[0-9]{2}[01][0-9]{4}))v[0-9]+$"
      }
    },

    "title": "Abs",
    "description": "Extended metadata record for an arXiv e-print.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "identifier",
      "content_type",
      "submitted_date",
      "announced_month",
      "license",
      "primary_classification",
      "title",
      "abstract",
      "authors_display",
      "authors"
    ],
    "properties": {
      "@type": {
        "type": "string"
      },
      "identifier": {
        "description": "Canonical arXiv e-print identifier",
        "$ref": "#/definitions/versioned_identifier"
      },
      "content_type": {
        "$ref": "#/definitions/content_type"
      },
      "is_withdrawn": {
        "type": "boolean"
      },
      "submitter": {
        "description": "The person who submitted the e-print.",
        "oneOf": [
          {"$ref": "#/definitions/person"},
          {"type": "null"}
        ]
      },
      "submitted_date": {
        "description": "Date this version of the e-print was submitted.",
        "type": "string",
        "format": "date-time"
      },
      "publication_date": {
        "description": "Date this e-print version was announced.",
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}$"
      },
      "announced_month": {
        "description": "Year and month (``%Y-%m``) this e-print version was announced.",
        "type": "string",
        "pattern": "^[0-9]{4}-[0-9]{2}$"
      },
      "license": {
        "$ref": "#/definitions/license"
      },
      "previous_versions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "identifier": {
              "description": "Canonical arXiv e-print identifier",
              "$ref": "#/definitions/versioned_identifier"
            },
            "submitted_date": {
              "description": "Date this version of the e-print was submitted.",
              "type": "string",
              "format": "date-time"
            },
            "announced_month": {
              "description": "Year and month (``%Y-%m``) this e-print version was announced.",
              "type": "string",
              "pattern": "^[0-9]{4}-[0-9]{2}$"
            },
            "source_type": {
              "type": "string"
            },
            "size_kilobytes": {
              "type": "number"
            }
          }
        }
      },
      "primary_classification": {
        "type": "string"
      },
      "secondary_classification": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "source_type": {
        "type": "string"
      },
      "size_kilobytes": {
        "type": "number"
      },
      "proxy": {
        "oneOf": [
          {"type": "string"},
          {"type": "null"}
        ]
      },
      "title": {
        "type": "string"
      },
      "abstract": {
        "type": "string"
      },
      "authors_display": {
        "descripiton": "Legacy author display string.",
        "type": "string"
      },
      "authors": {
        "type": "array",
        "minItems": 1,
        "items": {
          "$ref": "#/definitions/person"
        }
      },
      "collaborations": {
        "description": "Collaborations associated with this e-print",
        "type": "array",
        "items": {
          "$ref": "#/definitions/collaboration"
        }
      },
      "comments": {
        "oneOf": [
          {"type": "string"},
          {"type": "null"}
        ]
      },
      "journal_ref": {
        "description": "Journal reference",
        "oneOf": [
          {"type": "string"},
          {"type": "null"}
        ]
      },
      "report_num": {
        "oneOf": [
          {"type": "string"},
          {"type": "null"}
        ]
      },
      "publisher_doi": {
        "description": "The publisher-issued DOI(s).",
        "type": "array",
        "items": {
          "$ref": "#/definitions/doi"
        }
      },
      "arxiv_doi": {
        "description": "The arXiv-issued DOI.",
        "oneOf": [
          {"$ref": "#/definitions/doi"},
          {"type": "null"}
        ]
      },
      "msc_class": {
        "description": "Classifications from American Mathematical Society Mathematical Subject Classification (MSC)",
        "oneOf": [
          {"type": "string"},
          {"type": "null"}
        ]
      },
      "acm_class": {
        "description": "Classifications from ACM Computing Classification System",
        "oneOf": [
          {"type": "string"},
          {"type": "null"}
        ]
      }
    }
  }

=== arXiv/arxiv-canonical/schema-extended/example1.json
{
  "identifier": "2014.13925v1",
  "content_type": "article",
  "submitted_date": "2020-04-01T12:34:56Z",
  "announced_month": "2020-04",
  "license": {
    "href": "http://arxiv.org/licenses/nonexclusive-distrib/1.0/"
  },
  "title": "The Loudest Stellar Heartbeat: Characterizing the most extreme amplitude heartbeat star system",
  "primary_classification": "cs.AI",
  "abstract": "We characterize the extreme heartbeat star system MACHO 80.7443.1718 in the LMC using TESS photometry and spectroscopic observations from the Magellan Inamori Kyocera Echelle (MIKE) and SOAR Goodman spectographs. MACHO 80.7443.1718 was first identified as a heartbeat star system in the All-Sky Automated Survey for SuperNovae (ASAS-SN) with $P_{\\rm orb}=32.836\\pm0.008\\,{\\rm d}$. MACHO 80.7443.1718 is a young (${\\sim}6$~Myr), massive binary, composed of a B0 Iae supergiant with $M_1 \\simeq 35 M_\\odot$ and an O9.5V secondary with $M_2 \\simeq 16 M_\\odot$ on an eccentric ($e=0.51\\pm0.03$) orbit. In addition to having the largest variability amplitude amongst all known heartbeats stars, MACHO 80.7443.1718 is also one of the most massive heartbeat stars yet discovered. The B[e] supergiant has Balmer emission lines and permitted/forbidden metallic emission lines associated with a circumstellar disk. The disk rapidly dissipates at periastron which could indicate mass transfer to the secondary, but re-emerges immediately following periastron passage. MACHO 80.7443.1718 also shows tidally excited oscillations at the $N=25$ and $N=41$ orbital harmonics and has a rotational period of 4.4 d.",
  "authors_display": "T. Jayasinghe, C. S. Kochanek, J. Strader, K. Z. Stanek, P. J. Vallely, Todd A. Thompson, J. T. Hinkle, B. J. Shappee, A. K. Dupree, K. Auchettl, L. Chomiuk, E. Aydi, K. Dage, A. Hughes, L. Shishkovsky, K. V. Sokolovsky, S. Swihart, K. T. Voggel, I. B. Thompson",
  "authors": [
    {
      "full_name": "T. Jayasinghe",
      "first_name": "T.",
      "last_name": "Jayasinghe"
    },
    {
      "full_name": "C. S. Kochanek",
      "first_name": "C. S.",
      "last_name": "Kochanek"
    }
  ],
  "comments": "21 pages, 16 figures. Submitted to MNRAS"
}
